enrollsys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.homepage_view, name = 'home'),
    path('users/', include('users.urls')),
    path('courses/', include('courses.urls')),
    path('departments/', include('departments.urls')),
    path('curriculums/', include('curriculums.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('user/auth/login/', views.login_view, name = "login"),
    # path('user/auth/register/', views.register, name = 'register'), -- no need no more :>
    path('user/auth/logout/', views.logout_view, name = 'logout'),
    path('users/panel/<str:role>/', views.roles_view, name = 'panel'),
    path('users/add/<str:role>/', views.account_add_view, name = 'add'),
    path('user/profile/<int:user_id>/', views.profile_view, name = 'profile'),
    path('user/profile/edit/<int:user_id>/', views.profile_edit_view, name = 'profile-edit'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from departments.models import Department
# Create your models here.
class Teacher(models.Model):
    profile_img = models.ImageField(upload_to='users/profile_imgs/', default = 'users/profile_imgs/default.png')

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name = 'teacher')
    department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name= 'teachers')

    def __str__(self):
        parts = self.user.username.split('.')
        if len(parts) >= 2:
            first, last = parts[0].capitalize(), parts[1].capitalize()
        else:
            first, last = self.user.first_name, self.user.last_name
        return f"{first} {last}"
    

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs) # save teacher

        # get teacher group
        teacher_group, _ = Group.objects.get_or_create(name = 'Teacher') 

        # set corresp group
        self.user.groups.add(teacher_group)
    """ note:
        if department is deleted, teacher gets deleted, but user that
        corresponds to this teacher role is not deleted.
        This design has advantage, because user can get role teacher in
        another department without recreating its user account !    
    """

class Student(models.Model):
    profile_img = models.ImageField(upload_to='users/profile_imgs/', default = 'users/profile_imgs/default.png')
    student_id = models.AutoField(primary_key=True)
    program = models.ForeignKey('curriculums.Program', on_delete=models.PROTECT, null=True, related_name='students')
    gpa = models.FloatField(null = False)

    # ISA rel
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name= 'student')
    # studies_in rel
    department = models.ForeignKey(Department, on_delete=models.CASCADE, null = False, blank = False, related_name = 'advised_students')
    # advised_by rel
    advisor = models.ForeignKey(Teacher, on_delete=models.SET_NULL, null = True, related_name = 'advised_students')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs) # save student

        # automatically set corresponding group. (made for permissions handler)
        student_group, _ = Group.objects.get_or_create(name = 'Student')
        self.user.groups.add(student_group) # add group to created student

    def __str__(self):
        parts = self.user.username.split('.')
        if len(parts) >= 2:
            first, last = parts[0].capitalize(), parts[1].capitalize()
        else:
            first, last = self.user.first_name, self.user.last_name
        return f"{first} {last}"
    
class Registrar(models.Model):
    profile_img = models.ImageField(upload_to='users/profile_imgs/', default = 'users/profile_imgs/default.png')
    registrar_id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User ,on_delete=models.CASCADE, related_name= 'registrar')
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        # set registrar's group
        registrar_group, _ = Group.objects.get_or_create(name = 'Registrar')
        self.user.groups.add(registrar_group)

    def __str__(self):
        parts = self.user.username.split('.')
        if len(parts) >= 2:
            first, last = parts[0].capitalize(), parts[1].capitalize()
        else:
            first, last = self.user.first_name, self.user.last_name
        return f"{first} {last}"

users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms

from departments.models import Department
from .models import Teacher, Student, Registrar


class EnrollSysRegistrationForm(forms.Form):
    profile_img = forms.ImageField(
        required=False,
        label='Avatar',
        widget= forms.FileInput(attrs={'style': 'display: none;'})
    )
    name = forms.CharField(
        required = False, 
        label = 'First Name',
        widget = forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Your first name'})
    )

    surname = forms.CharField(
        required = False,
        label = 'Last Name',
        widget = forms.TextInput(attrs = {'class': 'form-input', 'placeholder': 'Your last name'})
    )

    email = forms.EmailField(
        required = False,
        label = 'Email',
        widget = forms.EmailInput(attrs = {'class': 'form-input' ,'placeholder': 'exampl@email.com'})
    )

    password = forms.CharField(
        required=False,
        widget=forms.PasswordInput(attrs={'class': 'form-input', 'placeholder': 'Password'})
    )

    ## used by Registrars ONLY ##
    ROLE_CHOICES = [
            ('teacher', 'Teacher'),
            ('student', 'Student'),
    ]

    role = forms.ChoiceField(
        choices = ROLE_CHOICES,
        label = 'Role',
        widget=forms.HiddenInput(),
        required=False
    )
    
    department = forms.ModelChoiceField(
        queryset= Department.objects.all(), 
        required = False,
        label = 'Department'
    )

    #############  ##############

    # -- CUSTOM initialization: --
    
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        
        if user:
            # dynamically add user attribute to form
            self.user_instance = user 

            if hasattr(user, 'student'):
                self.role = 'student'
                self.fields['department'].initial = user.student.department
                self.fields['profile_img'].initial = user.student.profile_img
                print('Editing Student')
            elif hasattr(user, 'teacher'):
                self.role = 'teacher'
                self.fields['department'].initial = user.teacher.department
                self.fields['profile_img'].initial = user.teacher.profile_img
                print('Editing Teacher')
            elif hasattr(user, 'registrar'):
                self.role = 'registrar'

            self.fields['name'].initial = user.first_name
            self.fields['surname'].initial = user.last_name
            self.fields['email'].initial = user.email

    # -- CUSTOM VALIDATION: --
    
    # avoid using same email twice.
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if hasattr(self, 'user_instance'): same_email = User.objects.all().exclude(pk = self.user_instance.pk).filter(email=email)
        else: same_email =User.objects.all().filter(email=email)
        
        if same_email.exists():
            raise forms.ValidationError('This email is not available !') # user already exists !
        return email
    
    
    def save(self, commit=True, user=None):
        if user is None:  # New user
            user = User(
                username=self.cleaned_data['email']
            )

        # Update attributes
        user.first_name = self.cleaned_data['name']
        user.last_name = self.cleaned_data['surname']
        user.email = self.cleaned_data['email']
        
        if self.cleaned_data['password']:
            user.set_password(self.cleaned_data['password'])

        # ------------------
        # Commit User
        # ------------------
        if commit:
            user.save()
            role = self.cleaned_data['role']
            if not role and hasattr(self, 'role'): role = self.role
            if role == 'student':
                student, created = Student.objects.get_or_create(
                    user=user,
                    defaults= {'gpa': 0.0, 'department': self.cleaned_data['department']}
                )
                if self.cleaned_data['profile_img']: student.profile_img = self.cleaned_data['profile_img']
                
                print('hereee')
                print(self.cleaned_data['profile_img'])
                student.save()

            elif role == 'teacher':
                teacher, created = Teacher.objects.get_or_create(
                    user=user,
                    defaults = {
                        'department': self.cleaned_data['department'],
                    }
                )
                if self.cleaned_data['profile_img']: teacher.profile_img = self.cleaned_data['profile_img']
                
                teacher.save()
            elif role == 'registrar':
                print(' at registrar!, cl: ', self.cleaned_data['profile_img'])
                registrar, _ = Registrar.objects.get_or_create(
                    user = user,
                )
                if self.cleaned_data['profile_img']: registrar.profile_img = self.cleaned_data['profile_img']
                registrar.save()
        return user

        

users/views.py
from django.shortcuts import render, redirect
from .forms import EnrollSysRegistrationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import Group, User
from django.contrib.auth import logout, login, authenticate
from .models import Student, Teacher
from curriculums.models import Program

# Create your views here.
def login_view(request):  # Renamed from 'login'
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)  # Using renamed import
                return redirect('/')
        # Add this to see errors in console for debugging
        print("Form errors:", form.errors)  
    else:
        form = AuthenticationForm()
    
    context = {
        'form': form,
    }
    return render(request, 'users/auth/login.html', context)  # Changed to login.html


def register(request):
    if request.method == 'POST':
        form = EnrollSysRegistrationForm(request.POST)
        if form.is_valid():
            # save user in model
            user = form.save()
            
            # automatically add to Student group
            student_group, is_first_student = Group.objects.get_or_create(name = "Student")
            user.groups.add(student_group)
            
            if is_first_student:
                print('\033[92mFirst student created!\033[0m')

            # automatically login after registering user
            login(request, user)
            return redirect('/')
    else:
        form = EnrollSysRegistrationForm()


    context = {
        'form': form
    }
    return render(request, 'users/auth/register.html', context)

def logout_view(request):
    logout(request)
    return redirect('/')


# show management panel for given role [REGISTRAR-ONLY]
def roles_view(request, role):
    context = {}
    context['role'] = role
    if role == 'student':
        context['students'] = Student.objects.all()
    elif role == 'teacher':
        context['teachers'] = Teacher.objects.all()
    return render(request, 'users/registrar/user_panel.html', context)

def account_add_view(request, role):
    context = {}
    context['role'] = role

    if role == 'student':
        context['students'] = Student.objects.all()
    elif role == 'teacher':
        context['teachers'] = Teacher.objects.all()
    context['form'] = EnrollSysRegistrationForm(initial = {'role': role})

    if request.method == 'POST':
        form = EnrollSysRegistrationForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('users:panel', role=role)
        else:
            print(form.errors)
    return render(request, 'users/registrar/user_panel.html', context)


# Profile page [COMMON]
def profile_view(request, user_id):
    user = User.objects.get(pk = user_id)
    context = {'user_viewed': user}
    return render(request, 'users/profile.html', context)


def profile_edit_view(request, user_id):
    user_under_edit = User.objects.get(pk = user_id)
    context = {'user_viewed': user_under_edit}

    form = EnrollSysRegistrationForm(user=user_under_edit)
    context['form'] = form

    if request.method == 'POST':
        # check for program change
        if hasattr(user_under_edit, 'student'):
            if(request.POST.get('program')):
                print('Program: ', request.POST.get('program'))
                updated_program = Program.objects.get(name = request.POST.get('program'))
                user_under_edit.student.program = updated_program
                user_under_edit.student.save()
                print('Saved Program!')
                
        # other attrib-s.
        form = EnrollSysRegistrationForm(request.POST, request.FILES ,user=user_under_edit)
        context['form'] = form

        if form.is_valid():
            form.save(user=user_under_edit)
            
            return redirect('users:profile', user_id=user_id)
        else:
            print(form.errors)

    # if editing student, pass programs of department
    if hasattr(user_under_edit, 'student'):
        context['programs'] = Program.objects.filter(department = user_under_edit.student.department)
    
    return render(request, 'users/profile.html', context)

users/templates/users/profile.html
{% extends 'layout.html' %}
{% load groupfilters %}
{% load static %}

{% block title %}Profile{% endblock %}
{% block extra_css %}
    <link rel = "stylesheet" href="{% static 'users/css/profile.css' %}"/>
{% endblock %}

{% block content %}
<div class="profile-container" style = "position:relative">

    <a href="{% url 'users:profile-edit' user_id=user_viewed.pk %}" class="edit-btn" title="Edit Profile">
        <i class="fas fa-edit me-1" style = "font-size: 2rem;"></i>
    </a>

    

    <!-- Extra Details -->

    {% if form %}
        <form class="profile-details" enctype="multipart/form-data" method = 'post' action = "{% url 'users:profile-edit' user_id=user_viewed.pk %}">
            {% csrf_token %}

            {% comment %} Profile Image {% endcomment %}
            <div class="position-relative d-inline-block">
                {% if user_viewed|has_group:'Student' %}
                    <img class="profile-img" src="{{ user_viewed.student.profile_img.url }}" alt="{{ user_viewed }}" />
                {% elif user_viewed|has_group:'Teacher' and user_viewed.teacher.profile_img %}
                    <img class="profile-img" src="{{ user_viewed.teacher.profile_img.url }}" alt="{{ user_viewed }}" />
                {% elif user_viewed|has_group:'Registrar' and user_viewed.registrar.profile_img %}
                    <img class="profile-img" src="{{ user_viewed.registrar.profile_img.url }}" alt="{{ user_viewed }}" />
                {% else %}
                    <img class="profile-img" src="{{ MEDIA_URL }}users/profile_imgs/default.png" alt="Default Avatar" />
                {% endif %}

                {% comment %} Browse File-Img Input {% endcomment %}
                <!-- Camera icon overlay -->
                <label for="{{ form.profile_img.id_for_label }}" class="avatar-upload-btn">
                    <i class="fas fa-camera"></i>
                </label>
                {{ form.profile_img }}
                
            </div>

            <!-- Name -->
            <div class="user-name">{{ user_viewed }}</div>

            <!-- Role Badge -->
            <div class="role-badge badge rounded-pill text-dark ms-2 small 
                {% if user_viewed|has_group:'Student' %}role-student
                {% elif user_viewed|has_group:'Teacher' %}role-teacher
                {% elif user_viewed|has_group:'Registrar' %}role-registrar
                {% elif user_viewed.is_superuser %}role-superuser
                {% else %}role-default
                {% endif %}">
                
                {% if user_viewed|has_group:'Student' %}
                    <i class="fas fa-user-graduate"></i> Student
                {% elif user_viewed|has_group:'Teacher' %}
                    <i class="fas fa-chalkboard-teacher"></i> Teacher
                {% elif user_viewed|has_group:'Registrar' %}
                    <i class="fas fa-user-shield"></i> Registrar
                {% elif user_viewed.is_superuser %}
                    <i class="fas fa-user-shield me-1"></i> Admin
                {% else %}
                    <i class="fas fa-user"></i> User
                {% endif %}
            </div>
            
            {% comment %} Profile Details {% endcomment %}
            <p><strong>Username:</strong> {{ user_viewed }}</p>

            {% if user|has_group:'Registrar' %}
                <p><strong>Name:</strong> {{ form.name }}</p>
                <p><strong>Surname:</strong> {{ form.surname }}</p>
            {% endif %}

            <p><strong>Email:</strong> {{ form.email }} </p>

            {% if user_viewed|has_group:"Student" %}
                <p><strong>GPA:</strong> {{ user_viewed.student.gpa }}</p>
                {% if user_viewed.student.advisor %}
                    <p><strong>Advisor:</strong> {{ user_viewed.student.advisor }}</p>
                {% endif %}

                {% if user_viewed.student.program and user|has_group:'Registrar' %}
                    <p><strong>Program:</strong>
                    <select name = 'program'>
                        {% for program in programs %}
                            <option value = '{{program.name}}' {% if user_viewed.student.program.name == program.name %}selected{% endif %}>{{program}}</option>
                        {% endfor %}
                    </select>
                {% endif %}
            {% elif user_viewed|has_group:"Teacher" %}
                <p><strong>Department:</strong> {{ form.department }}</p>
            {% endif %}

            <button>Apply Changes</button>
        </form>
    {% else %}
        <div class="position-relative d-inline-block">
            {% if user_viewed|has_group:'Student' %}
                <img class="profile-img" src="{{ user_viewed.student.profile_img.url }}" alt="{{ user_viewed }}" />
            {% elif user_viewed|has_group:'Teacher' and user_viewed.teacher.profile_img %}
                <img class="profile-img" src="{{ user_viewed.teacher.profile_img.url }}" alt="{{ user_viewed }}" />
            {% elif user_viewed|has_group:'Registrar' and user_viewed.registrar.profile_img %}
                <img class="profile-img" src="{{ user_viewed.registrar.profile_img.url }}" alt="{{ user_viewed }}" />
            {% else %}
                <img class="profile-img" src="{{ MEDIA_URL }}users/profile_imgs/default.png" alt="Default Avatar" />
            {% endif %}
        </div>
        
        <!-- Name -->
        <div class="user-name">{{ user_viewed }}</div>

        <!-- Role Badge -->
        <div class="role-badge badge rounded-pill text-dark ms-2 small 
            {% if user_viewed|has_group:'Student' %}role-student
            {% elif user_viewed|has_group:'Teacher' %}role-teacher
            {% elif user_viewed|has_group:'Registrar' %}role-registrar
            {% elif user_viewed.is_superuser %}role-superuser
            {% else %}role-default
            {% endif %}">
            
            {% if user_viewed|has_group:'Student' %}
                <i class="fas fa-user-graduate"></i> Student
            {% elif user_viewed|has_group:'Teacher' %}
                <i class="fas fa-chalkboard-teacher"></i> Teacher
            {% elif user_viewed|has_group:'Registrar' %}
                <i class="fas fa-user-shield"></i> Registrar
            {% elif user_viewed.is_superuser %}
                <i class="fas fa-user-shield me-1"></i> Admin
            {% else %}
                <i class="fas fa-user"></i> User
            {% endif %}
        </div>


    
        <div class="profile-details ">
            {% comment %} Common fields {% endcomment %}
            <p><strong>Username:</strong> {{ user_viewed }}</p>
            <p><strong>Name:</strong> {{ user_viewed.first_name }}</p>
            <p><strong>Surname:</strong> {{ user_viewed.last_name }}</p>
            <p><strong>Email:</strong> {{ user_viewed.email }} </p>

            {% if user_viewed|has_group:"Student" %}
                <p><strong>Department:</strong> {{ user_viewed.student.department.name }}</p>
                <p><strong>Program:</strong> {{user_viewed.student.program.name}}</p>
                <p><strong>GPA:</strong> {{ user_viewed.student.gpa }}</p>
                {% if user_viewed.student.advisor %}
                    <p><strong>Advisor:</strong> {{ user_viewed.student.advisor }}</p>
                {% endif %}
            {% elif user_viewed|has_group:"Teacher" %}
                <p><strong>Department:</strong> {{ user_viewed.teacher.department.name }}</p>
            {% endif %}
        </div>
    {% endif %}
    
</div>
{% endblock %}