courses/urls.py
from django.urls import path
from . import views
from django.conf import settings 
from django.conf.urls.static import static
app_name = 'courses'

urlpatterns = [
        # path('dashboard', views.sections_view, name = 'dashboard'), # for stud-s and teachers
        path('panel/', views.courses_and_sections_view, name = 'panel'), # management panel - should be secured
        path('panel/add/<str:type>/', views.courses_and_sections_view, name = 'add'),
        path('panel/add/<str:course_name>/<int:course_id>/', views.courses_and_sections_view, name = 'add-section'),
        path('panel/delete/<str:type>/<int:pk>', views.courses_and_sections_delete_view, name = 'delete'),
        path('panel/edit/<str:type>/<int:pk>', views.courses_and_sections_edit_view, name = 'edit'),
        # paths for Students and Teachers 
        path('my_sections/dashboard/', views.my_sections_view, name = 'my-sections')
    ]

departments/urls.py
from django.urls import path
from . import views

app_name = 'departments'

urlpatterns = [
    path('panel/', views.departments_view, name = 'panel'),
    path('panel/add', views.departments_add_view, name = 'add'),
    path('panel/edit/<int:dept_id>/', views.departments_edit_view, name = 'edit'),
    path('panel/delete/<int:dept_id>', views.departments_delete_view, name = 'delete'),
]

enrollsys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.homepage_view, name = 'home'),
    path('users/', include('users.urls')),
    path('courses/', include('courses.urls')),
    path('departments/', include('departments.urls')),
    path('curriculums/', include('curriculums.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('user/auth/login/', views.login_view, name = "login"),
    # path('user/auth/register/', views.register, name = 'register'), -- no need no more :>
    path('user/auth/logout/', views.logout_view, name = 'logout'),
    path('users/panel/<str:role>/', views.roles_view, name = 'panel'),
    path('users/add/<str:role>/', views.account_add_view, name = 'add'),
    path('user/profile/<int:user_id>/', views.profile_view, name = 'profile'),
    path('user/profile/edit/<int:user_id>/', views.profile_edit_view, name = 'profile-edit'),
]

departments/models.py
from django.db import models

# Create your models here.
class Department(models.Model):
    dept_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length= 30, unique = True, blank = False, null = False)

    def __str__(self):
        return f'{self.name}'

departments/forms.py
from django import forms
from .models import Department

class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ['name']

    # ValidationError - existing name
    def clean_name(self):
        inputed_name = self.cleaned_data.get('name')
        
        if Department.objects.exclude(dept_id = self.instance.dept_id).filter(name = inputed_name).exists():
            raise forms.ValidationError('Entered name alrady exists !')

        return inputed_name

departments/views.py
from django.shortcuts import render, redirect
from .models import Department
from .forms import DepartmentForm

# Create your views here.
def departments_view(request):
    context = {}
    departments = Department.objects.all()

    context['departments'] = departments
    return render(request, 'departments/departments_panel.html', context)

def departments_add_view(request):
    context = {}
    departments = Department.objects.all()
    context['departments'] = departments

    if request.method == 'POST':
        form = DepartmentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('departments:panel')
        else:
            print('Denied !')        
    else:
        form = DepartmentForm()
    context['form'] = form
    
    return render(request, 'departments/departments_panel.html', context)

def departments_edit_view(request, dept_id):
    context = {}
    departments = Department.objects.all()
    
    context['departments'] = departments
    context['editing_dept_id'] = dept_id
    department_to_edit = departments.get(dept_id = dept_id)

    if request.method == 'POST':
        form = DepartmentForm(request.POST, instance = department_to_edit)
        if form.is_valid():
            form.save()
            return redirect('departments:panel')
    
    print('dpt edt: ', department_to_edit)
    form = DepartmentForm(instance = department_to_edit)
    context['form'] = form

    return render(request, 'departments/departments_panel.html', context)

def departments_delete_view(request, dept_id):
    deleting_department = Department.objects.get(dept_id = dept_id)
    deleting_department.delete()
    return redirect('departments:panel')

departments/templates/departments/departments_panel.html
{% extends 'layout.html' %}
{% load static %}
{% block title %}
    Departments Panel
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'departments/css/styles.css' %}">
{% endblock %}
{% block content %}
<div class="panel-header d-flex justify-content-between align-items-center mb-4">
    <h1 class="m-0">Departments</h1>
    <a class="btn btn-success add-btn" href="{% url 'departments:add' %}" >
        <i class="fas fa-plus me-1"></i> Add Department
    </a>
</div>

<div class="panel-container">
    
    {% comment %} --FORM-- {% endcomment %}
    {% if form and not editing_dept_id %}
        <form class = 'department-card' method = 'post' action = "{% url 'departments:add' %}"/>
            {% csrf_token %}
            <h3 class="department-name">
                {{ form.name }}
                {% if form.name.errors %}
                    <div class="error-message">
                        {{ form.name.errors.0 }}
                    </div>
                {% endif %}
            </h3>
            <div class="department-buttons">
                <a class="btn add-btn" href="{% url 'departments:add' %}">
                    <i class="fas fa-building me-1"></i> Add Department
                </a>
            </div>
        </form>
    {% endif %}

    {% for department in departments %}
        {% if department.dept_id == editing_dept_id %}
            <form class = 'department-card' method = 'post' action = "{% url 'departments:edit' dept_id=editing_dept_id%}"/>
                {% csrf_token %}
                <h3 class="department-name">
                    {{ form.name }}
                    {% if form.name.errors %}
                        <div class="error-message">
                            {{ form.name.errors.0 }}
                        </div>
                    {% endif %}
                </h3>
                <div class="department-buttons">
                    <button class="btn add-btn" href="{% url 'departments:edit' dept_id=department.dept_id %}">
                        <i class="fas fa-building me-1"></i> save changes
                    </button>
                </div>
            </form>
        {% else %}
            <div class="department-card">
                <h3 class="department-name">{{ department.name }}</h3>
                <div class="department-buttons">
                    <a href="{% url 'departments:edit' dept_id=department.dept_id %}" class="btn btn-edit">
                        <i class="fas fa-pen"></i> Edit
                    </a>
                    <a href="#" class="btn btn-delete"
                        onclick="if(confirm('Are you sure you want to delete this department?')) { window.location.href='{% url 'departments:delete' dept_id=department.dept_id %}'; }">
                        <i class="fas fa-trash-alt me-1"></i> Delete
                        </a>
                    <form method="get" action="{% url 'courses:panel' %}" class="btn btn-courses">
                        <input type="hidden" name="department" value="{{ department.dept_id }}">
                        <button type="submit" style="background: none; border: none; padding: 0; cursor: pointer;">
                            <i class="fas fa-book"></i> Courses
                        </button>
                    </form>
                </div>
            </div>
        {% endif %}
    {% endfor %}
</div>
{% endblock %}